name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        command: install

    - name: Check CS
      uses: php-actions/composer@v6
      with:
        command: check-cs

    - name: Validate Composer
      uses: php-actions/composer@v6
      with:
        command: validate
