name: Validate Composer Config
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
    - name: Validate Composer Config
      run: |
        composer validate --strict
